import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./global-components/Navbar";
import { MenuProvider } from "@/context/MenuContext";
import { ThemeProvider } from "./global-components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/context/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider>
            <MenuProvider>
              <Toaster richColors position="top-right" />
              <Navbar />

              {children}

            </MenuProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
